# Generated by Django 4.2.1 on 2023-05-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataScraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(max_length=1000)),
                ('anchor', models.TextField(max_length=1000)),
                ('title', models.TextField(max_length=1000)),
            ],
        ),
    ]
